spring.application.name=Spring_Batch


spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash-lite






# Disable automatic batch execution on startup
spring.batch.job.enabled=false

# Disable default DataSource auto-configuration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Automatically initialize Spring Batch metadata tables if not present
spring.batch.jdbc.initialize-schema=always